# Generated by Django 4.0.4 on 2022-06-03 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('zone_geographique', models.CharField(max_length=255, verbose_name='Zone Géographique')),
                ('description', models.CharField(max_length=255, verbose_name='Description du projet')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('s_zone', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_couverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_ul', models.FloatField(null=True)),
                ('pout_ms', models.FloatField(null=True)),
                ('pout_bs', models.FloatField(null=True)),
                ('ga_bs', models.FloatField(null=True)),
                ('ga_ms', models.FloatField(null=True)),
                ('lf_bs', models.FloatField(null=True)),
                ('lf_ms', models.FloatField(null=True)),
                ('mf', models.FloatField(null=True)),
                ('ml', models.FloatField(null=True)),
                ('lp', models.FloatField(null=True)),
                ('lb', models.FloatField(null=True)),
                ('s_bs', models.FloatField(null=True)),
                ('s_ms', models.FloatField(null=True)),
                ('mpc', models.FloatField(null=True)),
                ('eb_nt', models.FloatField(null=True)),
                ('w', models.FloatField(null=True)),
                ('rb', models.FloatField(null=True)),
                ('kt', models.FloatField(null=True)),
                ('pl_dl', models.FloatField(null=True)),
                ('nf_bs', models.FloatField(null=True)),
                ('pl', models.FloatField(null=True)),
                ('modele_propagation', models.CharField(max_length=255, null=True)),
                ('rayon', models.FloatField(null=True)),
                ('hm', models.FloatField(null=True)),
                ('hb', models.FloatField(null=True)),
                ('heff', models.FloatField(null=True)),
                ('ahm', models.FloatField(null=True)),
                ('cm', models.FloatField(null=True)),
                ('f', models.FloatField(null=True)),
                ('s_cell_ul', models.FloatField(null=True)),
                ('s_cell_dl', models.FloatField(null=True)),
                ('d_inter_site', models.FloatField(null=True)),
                ('n_site_ul', models.FloatField(null=True)),
                ('n_site_dl', models.FloatField(null=True)),
                ('nb_sites', models.IntegerField(verbose_name='Nombre de sites')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btssizing_app.projet')),
            ],
        ),
    ]
