# Generated by Django 4.0.4 on 2022-06-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btssizing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_couverture',
            name='nb_sites',
            field=models.IntegerField(null=True, verbose_name='Nombre de sites'),
        ),
    ]
