# Generated by Django 4.0.4 on 2022-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btssizing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_capacite',
            name='nb_sites_capacite',
            field=models.FloatField(null=True),
        ),
    ]
