# Generated by Django 4.0.4 on 2022-06-04 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btssizing_app', '0003_alter_plan_couverture_projet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan_couverture',
            old_name='ml',
            new_name='mi',
        ),
        migrations.RenameField(
            model_name='plan_couverture',
            old_name='rayon',
            new_name='r',
        ),
    ]
